### ISSUE TITLE
Segmentation Fault with 1.1.2 / 1.1.3

### ISSUE THREAD

**Issue by EugenMayer** [mongodb/mongo-php-driver#258] opened 2016-03-09 11:25 UTC
**System**
Wheezy
PHP: PHP 5.5.33-1~dotdeb+7.1
ext/mongdb: 1.1.3

activated modules: http://pastie.org/10753407
module versions ( pecl ): http://pastie.org/10753408

**Details/Reproduction:**
Whenever i activate the mongodb extension, the segmentation faults will start after a while - disabling the module removes this behaviour.
Our app does neither need to use the mongodb extension at all, fpm will crash after a while. This is not related to any PHP code or connection strings, this is plainly crashing out of any reason.

What is needed tough is, using FPM by any sort of PHP app, to i guess let the garbage collector do stuff, until _mongoc_do_cleanup does something silly, whatever that might be.

best

**Core-Dump**
(also attached)
`
gdb /usr/sbin/php5-fpm /tmp/coredump-php5-fpm.7493
Reading symbols from /usr/sbin/php5-fpm...Reading symbols from /usr/lib/debug/usr/sbin/php5-fpm...done.
done.
[New LWP 7493]
Program terminated with signal 11, Segmentation fault.
#0  zend_mm_remove_from_free_list (heap=0x2ce0300, mm_block=0x5b6e940) at /usr/src/builddir/Zend/zend_alloc.c:837
837	/usr/src/builddir/Zend/zend_alloc.c: No such file or directory.
(gdb) bt
#0  zend_mm_remove_from_free_list (heap=0x2ce0300, mm_block=0x5b6e940) at /usr/src/builddir/Zend/zend_alloc.c:837
#1  0x00000000006c6ef0 in _zend_mm_free_int (heap=0x2ce0300, p=0x2db2640) at /usr/src/builddir/Zend/zend_alloc.c:2105
#2  0x00007f773ee38cdb in ?? () from /usr/lib/x86_64-linux-gnu/sasl2/libdigestmd5.so
#3  0x00007f7746d7ba81 in ?? () from /usr/lib/x86_64-linux-gnu/libsasl2.so.2
#4  0x00007f7746d7bb02 in sasl_client_done () from /usr/lib/x86_64-linux-gnu/libsasl2.so.2
#5  0x00007f773f2a8d7e in _mongoc_do_cleanup () at /tmp/pear/temp/mongodb/src/libmongoc/src/mongoc/mongoc-init.c:130
#6  0x00007f774968b8a0 in pthread_once () from /lib/x86_64-linux-gnu/libpthread.so.0
#7  0x00007f774cabc49c in ?? () from /lib64/ld-linux-x86-64.so.2
#8  0x00007f7749ae7aa2 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#9  0x00007f7749ae7af5 in exit () from /lib/x86_64-linux-gnu/libc.so.6
#10 0x00007f7749acfeb4 in __libc_start_main () from /lib/x86_64-linux-gnu/libc.so.6
#11 0x0000000000471dfd in _start ()

`

`

(gdb) frame 11
#11 0x0000000000471dfd in _start ()
(gdb) info frame
Stack level 11, frame at 0x7ffce9f3f448:
 rip = 0x471dfd in _start; saved rip 0x7ffce9f3f448
 caller of frame at 0x7ffce9f3f440
 Arglist at 0x7ffce9f3f438, args:
 Locals at 0x7ffce9f3f438, Previous frame's sp is 0x7ffce9f3f448
 Saved registers:
  rip at 0x7ffce9f3f440
(gdb) info locals
No symbol table info available.
(gdb) info args
No symbol table info available.
`

**Comment by amikheychik** [comment] 2016-03-10 06:41
Have the same problem, but in my case the object I was trying to write had a recursion, so it makes why it fails.
I think it will be nice if driver will be able to detect recursions, as some objects in the system may come from 3rd party vendors with little control over them.

**Comment by EugenMayer** [comment] 2016-03-10 10:29
@amikheychik i think your issues is very different. You actually do use the mongodb binding and then it fails, this issue is rather about **not using** the driver, only loading it - and this will start crashing you FPM server. So it is impossible that a PHP issue leads to this issue.

**Comment by derickr** [comment] 2016-03-10 11:59
Could be related to #209

**Comment by jmikola** [comment] 2016-03-18 16:45
Confirmed that this issue is a duplicate of #209. Tracking in [PHPC-632](https://jira.mongodb.org/browse/PHPC-632).

@amikheychik: Your issue is indeed very different. Please see [PHPC-276](https://jira.mongodb.org/browse/PHPC-276) for a tracking ticket on detect recursion during BSON serialization.

**Closed** 2016-03-18 16:59 UTC
Labels: bug

**Comment by jmikola** [comment] 2016-03-18 18:38
[1.1.5](https://github.com/mongodb/mongo-php-driver/releases/tag/1.1.5) has been tagged with the fix for those using bundled libmongoc. Please note that using libmongoc as a system library will require an upstream fix (see: [CDRIVER-1165](https://jira.mongodb.org/browse/CDRIVER-1165)), so folks in that camp may want to switch to using bundled libmongoc for the time being.
