### ISSUE TITLE
configure: error: Cannot find OpenSSL's <evp.h>

### ISSUE THREAD

**Issue by rahulgupta20nov** [mongodb/mongo-php-driver#363] opened 2016-08-01 11:30 UTC
WHen I am trying to install mongodb driver using pecl in MAC. its gives error like that atlast:-

configure: error: Cannot find OpenSSL's <evp.h>
ERROR: `/private/tmp/pear/temp/mongodb/configure --with-php-config=/usr/local/Cellar/php70/7.0.9/bin/php-config' failed

But I have installed openssl in my system. I am not getting whats the problem.
Please help.

If there have any way to install without using pecl, then tell me.

**Comment by jmikola** [comment] 2016-08-01 17:50
This is a duplicate of https://github.com/mongodb/mongo-php-driver/issues/299.

As noted there, this appears to be an issue with PHP's build functions that search for OpenSSL. Installing `pkg-config` may help. Please follow up in https://github.com/mongodb/mongo-php-driver/issues/299 to consolidate discussion around the issue.

**Comment by rahulgupta20nov** [comment] 2016-08-01 18:07
Thanks jmikola,
I installed a package is "pkg-config". So issue has resolved. But after that I got different issue.

OMPILATION -DMONGOC_TRACE -DHAVE_CONFIG_H -g -O0 -D_THREAD_SAFE -pthread -c /private/tmp/pear/install/mongodb/src/contrib/php-ssl.c  -fno-common -DPIC -o src/contrib/.libs/php-ssl.o
In file included from /private/tmp/pear/install/mongodb/src/contrib/php-ssl.c:31:
/private/tmp/pear/install/mongodb/src/contrib/php-ssl.h:33:10: fatal error: 'openssl/evp.h' file not found
#include <openssl/evp.h>
         ^
1 error generated.
make: *** [src/contrib/php-ssl.lo] Error 1
ERROR: `make' failed

**Comment by bjori** [comment] 2016-08-01 18:16
OSX no longer ships the OpenSSL developers headers, only the runtime library.

Try
```
$ brew install openssl
$ export LDFLAGS="-L/usr/local/opt/openssl/lib"
$ export CFLAGS="-I/usr/local/opt/openssl/include"
$ pecl install mongodb
```

This will no longer be necessary when the drivers witches away from PHP streams to using the `mongoc` provided Native TLS, which does not rely on OpenSSL

**Comment by rahulgupta20nov** [comment] 2016-08-01 18:22
I have checked, openssl is installed in my system.

I followed above steps but above problem is not resolved.

What I need to  do for ignore this error. I am not php guy but need to deploy backend in my system.

**Comment by rahulgupta20nov** [comment] 2016-08-01 18:41
I have tried to install mongodb-1.1.7 & mongodb-1.1.6, 
But same error is coming.

**Comment by rahulgupta20nov** [comment] 2016-08-01 18:46
this is the end part of the error.  

> -pthread  -c /private/tmp/pear/install/mongodb/src/contrib/php-ssl.c -o src/contrib/php-ssl.lo
mkdir src/contrib/.libs
 cc -I. -I/private/tmp/pear/install/mongodb -DPHP_ATOM_INC -I/private/tmp/pear/install/pear-build-rootmzIuF1/mongodb-1.1.6/include -I/private/tmp/pear/install/pear-build-rootmzIuF1/mongodb-1.1.6/main -I/private/tmp/pear/install/mongodb -I/usr/local/Cellar/php70/7.0.9/include/php -I/usr/local/Cellar/php70/7.0.9/include/php/main -I/usr/local/Cellar/php70/7.0.9/include/php/TSRM -I/usr/local/Cellar/php70/7.0.9/include/php/Zend -I/usr/local/Cellar/php70/7.0.9/include/php/ext -I/usr/local/Cellar/php70/7.0.9/include/php/ext/date/lib -I/usr/local/include -I/usr -I/private/tmp/pear/install/mongodb/src/BSON/ -I/private/tmp/pear/install/mongodb/src/MongoDB/ -I/private/tmp/pear/install/mongodb/src/MongoDB/Exception/ -I/private/tmp/pear/install/mongodb/src/contrib/ -I/private/tmp/pear/install/mongodb/src/libmongoc/src/mongoc/ -I/private/tmp/pear/install/mongodb/src/libbson/src/ -I/private/tmp/pear/install/mongodb/src/libbson/src/yajl/ -I/private/tmp/pear/install/mongodb/src/libbson/src/bson/ -DBSON_COMPILATION -DMONGOC_C
OMPILATION -DMONGOC_TRACE -DHAVE_CONFIG_H -g -O0 -D_THREAD_SAFE -pthread -c /private/tmp/pear/install/mongodb/src/contrib/php-ssl.c  -fno-common -DPIC -o src/contrib/.libs/php-ssl.o
In file included from /private/tmp/pear/install/mongodb/src/contrib/php-ssl.c:31:
/private/tmp/pear/install/mongodb/src/contrib/php-ssl.h:33:10: fatal error: 'openssl/evp.h' file not found
#include <openssl/evp.h>
         ^
1 error generated.
make: *** [src/contrib/php-ssl.lo] Error 1
ERROR: `make' failed

**Comment by lanlin** [comment] 2016-09-29 10:06
I have the same problem, and tried many ways, still not be resolved.

**Comment by lenmen** [comment] 2016-10-04 19:14
I got that problem too. When I looked at the answer at stackoverflow and the answer on that question worked for me.

http://stackoverflow.com/questions/33483210/using-pecl-to-install-the-mongodb-driver-on-os-x-el-capitan-v10-11-1 

might work on you're case too.

**Comment by etreby** [comment] 2017-03-09 15:53
i fixit by simply installing pkg-config
$ brew install pkg-config
$ pecl install mongodb

**Comment by zhangxiaoda** [comment] 2017-03-13 09:04
@etreby 
Thank you, your answer solved my question

**Comment by mertmetin** [comment] 2017-04-17 20:59
pkg-config solved the problem. However, when you build pkg-config, use the internal glip, if you face the glip version.

sudo make install --with-internal-glib

**Comment by jmikola** [comment] 2017-04-28 14:58
The suggestion to install `pkg-config` is documented in the [installation docs for PECL](http://php.net/manual/en/mongodb.installation.pecl.php), so I don't think there's anything to address here.

**Closed by jmikola** 2017-04-28 14:58 UTC

**Comment by Webhero9297** [comment] 2017-10-19 16:30
?

**Comment by webeautiful** [comment] 2018-05-11 01:42
@lenmen
Thank you, I resolved below:

> ln -s /usr/local/Cellar/openssl/1.0.2m/include/openssl

**Comment by 852208555** [comment] 2020-03-05 14:37
I resolved this question in mac below:
brew install openssl 
and replace the XXX to you installed's version of the openssl
ln -s  /usr/local/Cellar/openssl@XX/xxx/include/openssl /usr/local/include/openssl
and it will be ok
