### ISSUE TITLE
Is it difficult adding a close() method? Why there is no method of turning off connection?

### ISSUE THREAD

**Issue by udoless** [mongodb/mongo-php-driver#396] opened 2016-09-08 11:49 UTC
Why there is no method of turning off connection? 
If I want to add a close() method, is it difficult?

**Comment by jmikola** [comment] 2016-09-08 15:18
Duplicate of https://github.com/mongodb/mongo-php-driver/issues/393.

**Closed by jmikola** 2016-09-08 15:18 UTC

**Comment by ar414-com** [comment] 2020-03-17 04:34
If I want to add a close() method, is it difficult?
