### ISSUE TITLE
countDocuments() throws CommandException  unrecognized field 'hint'

### ISSUE THREAD

**Issue by camohub** [mongodb/mongo-php-driver#980] opened 2019-05-17 07:49 UTC
Hi, I need to count documents because paginator. So tried to use Collection::countDocuments() to get the number of documetns. Command looks like:

````$count = $this->organizationCollection->countDocuments([], ['hint' => 'ico']);````

But this command throws me an error: **MongoDB\Driver\Exception\CommandException unrecognized field 'hint'**
Haw can I fix it?

**Comment by jmikola** [comment] 2019-05-17 13:15
The `Collection::countDocument()` method uses an [aggregation pipeline internally](https://docs.mongodb.com/php-library/current/reference/method/MongoDBCollection-countDocuments/#behavior), so the error you're seeing is caused by the underlying [`aggregate`](https://docs.mongodb.com/manual/reference/command/aggregate/) command not supporting a `hint` option. According to the MongoDB manual, the `hint` option was introduced to `aggregate` in server version 3.6.

You didn't specify the version of MongoDB you are using, but if it is 3.4.x or earlier then the CommandException would be expected behavior.

**Comment by camohub** [comment] 2019-05-17 13:19
Yes Mongo version is 3.4 Thnaks.

**Comment by jmikola** [comment] 2019-05-17 16:21
Thanks for the quick follow-up. If you absolutely need to hint an index, you can consider using the deprecated [`Collection::count()`](https://docs.mongodb.com/php-library/current/reference/method/MongoDBCollection-count/) method, which uses the [`count`](https://docs.mongodb.com/manual/reference/command/count/) command. Just be aware of its [edge cases](https://docs.mongodb.com/manual/reference/command/count/#behavior), which may or may not apply to your use case.

I'll close this issue as I don't believe there's anything left to address.

**Closed by jmikola** 2019-05-17 16:21 UTC
