### ISSUE TITLE
Unable to load dynamic library after upgrade to 1.2.0 "undefined symbol: php_json_serializable_ce"

### ISSUE THREAD

**Issue by stephadz** [mongodb/mongo-php-driver#477] opened 2016-11-30 13:44 UTC
### Description
After upgrade driver to release 1.2.0, i've got an error at apache startup and cli : 

PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib64/php/5.6/modules/mongodb.so' - /usr/lib64/php/5.6/modules/mongodb.so: undefined symbol: php_json_serializable_ce in Unknown on line 0

No problem when i downgrade to 1.1.9

### Environment

We use preconfigured AWS environnement : 64bit Amazon Linux 2016.09 v2.2.0 running PHP 5.6
PHP 5.6.26
Apache 2.4.23

### Tests / debug

On release 1.2.0 
```
$ php -i | grep -E 'mongodb|libmongoc|libbson'
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib64/php/5.6/modules/mongodb.so' - /usr/lib64/php/5.6/modules/mongodb.so: undefined symbol: php_json_serializable_ce in Unknown on line 0

```

After downgrading to 1.1.9
```
$ php -i | grep -E 'mongodb|libmongoc|libbson'
mongodb
mongodb support => enabled
mongodb version => 1.1.9
mongodb stability => stable
libmongoc version => 1.3.6
libbson version => 1.3.6
mongodb.debug => no value => no value

```

i hope i have provided you with sufficient information

Thanks

**Comment by jmikola** [comment] 2016-11-30 14:13
This is likely a duplicate of https://github.com/mongodb/mongo-php-driver/issues/475. @derickr is in the process of writing a blog post to discuss the issue in more detail.

This is related to a new dependency on the `json` extension in 1.2.0, as our BSON classes now implement JsonSerializable ([PHPC-459](https://jira.mongodb.org/browse/PHPC-459)). We likewise declare dependencies on the `date` and `spl` extensions for UTCDateTime and our exceptions, respectively; however, those are almost always compiled into PHP. The `json` extension is sometimes loaded dynamically by different distributions. Those distributions may also elect to resolve symbols at execution time instead of lazily during runtime (PHP's default behavior), which can cause this error.

Please confirm whether the `json` extension is compiled into PHP or if you're loading it a `json.so` file dynamically in your PHP configuration. Assuming the latter, you need to ensure that the extension is loaded before `mongodb.so`.

**Comment by derickr** [comment] 2016-11-30 14:58
The blog post is up at https://derickrethans.nl/undefined-symbol.html

**Comment by hotrush** [comment] 2016-12-02 11:23
same error with `PHP 7.0.13-1+deb.sury.org~trusty+1`  and ubuntu 14.04. 1.1.9 works

**Comment by derickr** [comment] 2016-12-02 12:35
@hotrush We know, but this is not something we *can* fix. Please read the blog post at https://derickrethans.nl/undefined-symbol.html for the reasons why.

I am closing this ticket, as there is nothing to be done here.

**Closed by derickr** 2016-12-02 12:35 UTC
