### ISSUE TITLE
Can't load module on Mac OS X 10.14.6 and PHP 7.4.2

### ISSUE THREAD

**Issue by pesseyjulien** [mongodb/mongo-php-driver#1106] opened 2020-02-28 20:07 UTC
HI,

Followed both the manual installation guide and the pecl installation guide, no errors but then the extension is not loaded :

```
[28-Feb-2020 18:55:09 UTC] PHP Warning:  PHP Startup: Unable to load dynamic library '/Applications/MAMP/bin/php/php7.4.2/lib/php/extensions/no-debug-non-zts-20190902/mongodb.so' (tried: /Applications/MAMP/bin/php/php7.4.2/lib/php/extensions/no-debug-non-zts-20190902/mongodb.so (dlopen(/Applications/MAMP/bin/php/php7.4.2/lib/php/extensions/no-debug-non-zts-20190902/mongodb.so, 9): Library not loaded: libicuuc.56.dylib
  Referenced from: /Applications/MAMP/bin/php/php7.4.2/lib/php/extensions/no-debug-non-zts-20190902/mongodb.so
  Reason: image not found), /Applications/MAMP/bin/php/php7.4.2/lib/php/extensions/no-debug-non-zts-20190902///Applications/MAMP/bin/php/php7.4.2/lib/php/extensions/no-debug-non-zts-20190902/mongodb.so.so (dlopen(/Applications/MAMP/bin/php/php7.4.2/lib/php/extensions/no-debug-non-zts-20190902///Applications/MAMP/bin/php/php7.4.2/lib/php/extensions/no-debug-non-zts-20190902/mongodb.so.so, 9): image not found)) in Unknown on line 0
```

My config :

```
php --ini
Configuration File (php.ini) Path: /Applications/MAMP/bin/php/php7.4.2/conf
Loaded Configuration File:         /Applications/MAMP/bin/php/php7.4.2/conf/php.ini
Scan for additional .ini files in: (none)
Additional .ini files parsed:      (none)
```

```
$_SERVER['argc'] => 0
$_ENV['TERM_SESSION_ID'] => w0t2p0:BE719AFA-1092-4BC8-BD44-C115D9DB954C
$_ENV['SSH_AUTH_SOCK'] => /private/tmp/com.apple.launchd.UufSiC0shx/Listeners
$_ENV['LC_TERMINAL_VERSION'] => 3.3.8beta5
$_ENV['Apple_PubSub_Socket_Render'] => /private/tmp/com.apple.launchd.VKFQInWY9g/Render
$_ENV['COLORFGBG'] => 12;8
$_ENV['ITERM_PROFILE'] => Default
$_ENV['XPC_FLAGS'] => 0x0
$_ENV['LANG'] => fr_FR.UTF-8
$_ENV['PWD'] => /Applications/MAMP/bin/php/php7.4.2/lib/php/extensions/no-debug-non-zts-20190902
$_ENV['SHELL'] => /bin/zsh
$_ENV['TERM_PROGRAM_VERSION'] => 3.3.8beta5
$_ENV['TERM_PROGRAM'] => iTerm.app
$_ENV['PATH'] => /Applications/MAMP/bin/php/php7.4.2/bin:/Applications/Postgres.app/Contents/Versions/latest/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Applications/Postgres.app/Contents/Versions/latest/bin
$_ENV['LC_TERMINAL'] => iTerm2
$_ENV['COLORTERM'] => truecolor
$_ENV['TERM'] => xterm-256color
$_ENV['HOME'] => /Users/pessey
$_ENV['TMPDIR'] => /var/folders/m9/tnb9cx451tg2tf884fp7k7100000gn/T/
$_ENV['USER'] => pessey
$_ENV['XPC_SERVICE_NAME'] => 0
$_ENV['LOGNAME'] => pessey
$_ENV['ITERM_SESSION_ID'] => w0t2p0:BE719AFA-1092-4BC8-BD44-C115D9DB954C
$_ENV['__CF_USER_TEXT_ENCODING'] => 0x1F5:0x0:0x1
$_ENV['SHLVL'] => 1
$_ENV['OLDPWD'] => /Users/pessey
$_ENV['ZSH'] => /Users/pessey/.oh-my-zsh
$_ENV['PAGER'] => less
$_ENV['LESS'] => -R
$_ENV['LSCOLORS'] => Gxfxcxdxbxegedabagacad
$_ENV['_'] => /Applications/MAMP/bin/php/php7.4.2/bin/php
```

Any idea what is going on ?

Thanks in advance,
Julien

**Comment by alcaeus** [comment] 2020-03-02 07:03
> Library not loaded: libicuuc.56.dylib

It looks like the icu library was not found on your system. On MacOS, you can install it using hombrew by running `brew install icu4c`, which should solve your problem. Please let me know if it doesn't.

**Comment by pesseyjulien** [comment] 2020-03-02 09:15
Hi,

Thanks but it's installed (see screenshot). I have no problem installing and loading the driver with php7.2.1, but the same version does not work with php7.4.2

![Capture d’écran 2020-03-02 à 10 14 28](https://user-images.githubusercontent.com/10850944/75662028-b4efe500-5c6e-11ea-88a4-6371a1545666.jpg)

**Comment by alcaeus** [comment] 2020-03-02 09:26
You mention that it works on PHP 7.2.1, but fails on 7.4. Can you please confirm that pecl is indeed compiling against PHP 7.4 and putting the compiled module in the correct folder? I'm not familiar with how MAMP handles multiple versions, so I'm not entirely sure what the cause could be.

**Comment by pesseyjulien** [comment] 2020-03-02 10:02
Yeah I did that too, I don't have the versio 7.4 installed anymore, I had to rollback so I could continue to work. But when I did phpize and php -i, the version matched.

**Comment by alcaeus** [comment] 2020-03-23 12:59
@pesseyjulien I didn't manage to reproduce it on PHP 7.4, does the error still appear on your system when you try to install the extension on 7.4??

**Comment by pesseyjulien** [comment] 2020-03-23 15:03
Hi, did not try again, maybe this week if I have some extra hours on hand.

**Comment by pesseyjulien** [comment] 2020-03-28 10:06
@alcaeus Still the same issue :

`PHP Warning:  PHP Startup: Unable to load dynamic library 'mongodb.so' (tried: /Applications/MAMP/bin/php/php7.4.2/lib/php/extensions/no-debug-non-zts-20190902/mongodb.so (dlopen(/Applications/MAMP/bin/php/php7.4.2/lib/php/extensions/no-debug-non-zts-20190902/mongodb.so, 9): Library not loaded: libicuuc.56.dylib
  Referenced from: /Applications/MAMP/bin/php/php7.4.2/lib/php/extensions/no-debug-non-zts-20190902/mongodb.so
  Reason: image not found), /Applications/MAMP/bin/php/php7.4.2/lib/php/extensions/no-debug-non-zts-20190902/mongodb.so.so (dlopen(/Applications/MAMP/bin/php/php7.4.2/lib/php/extensions/no-debug-non-zts-20190902/mongodb.so.so, 9): image not found)) in Unknown on line 0
`

I upgrade my OS to the latest version (Mac OS Catalina 10.15.4), reinstalled php7.4.2, then installed mongodb via PECL (no error) but when I add the 'extension=mongodb.so' to the php.ini, I get this error. 
Frustrating !

**Comment by pesseyjulien** [comment] 2020-03-28 10:07
And yes, the extension does exist ;) 

![Capture d’écran 2020-03-28 à 11 06 59](https://user-images.githubusercontent.com/10850944/77820686-46bf0680-70e4-11ea-9cfc-45037fd15812.jpg)

**Comment by pesseyjulien** [comment] 2020-03-28 10:12
More infos :

![Capture d’écran 2020-03-28 à 11 11 59](https://user-images.githubusercontent.com/10850944/77820775-001ddc00-70e5-11ea-92fb-be2a1cc70f5c.jpg)
![Capture d’écran 2020-03-28 à 11 09 59](https://user-images.githubusercontent.com/10850944/77820777-0318cc80-70e5-11ea-838a-f199a07bc86e.jpg)
![Capture d’écran 2020-03-28 à 11 08 39](https://user-images.githubusercontent.com/10850944/77820779-03b16300-70e5-11ea-9030-507518b0bd67.jpg)

**Comment by alcaeus** [comment] 2020-03-30 12:20
Thanks for providing the information. A few things:
* The MongoDB extension does not have a dependency on icu4c. Instead, the various ICU libs are required for PHP itself. For example, the php package on homebrew [lists `icu4c` as a dependency](https://github.com/Homebrew/homebrew-core/blob/fd3c66a099d64526a3d7e3604184e88e4b3aa69a/Formula/php.rb#L34).
* Homebrew currently ships icu4c version 64.2. Your PHP package is looking for version 56, which was released in 2015 and is well outdated. It looks like your MAMP release was compiled against this old version which is not found on your system. I would suggest to check the MAMP support resources for help with that problem.

As a different alternative, you can try installing php via homebrew and testing the extension against that. Please make sure that you're indeed calling php from homebrew (in `/usr/local/bin/php` and `/usr/local/bin/pear`), and not from MAMP (in `/Applications/MAMP/...`)
You can try to install PHP from homebrew and build the MongoDB extension against that.

**Comment by pesseyjulien** [comment] 2020-03-30 16:25
Hi, thanks for the feedback. I will contact MAMP support see if it's coming from their end, but I'm already using MAMP v4, php7.2.1, and I have no error when installing the mongodb extension from pecl.

It happens when I upgrade to MAMPv5 and php7.4.2, so you might be right but after digging into the phpinfo() I can see icu 56.1 and libmongo ICU enable (below screenshots) whereas I have icu4c 64.2 installed with homebrew.

I would like to keep using MAMP,  I have multiple projects with different hosts/php versions and they do manage this pretty good.

![Capture d’écran 2020-03-30 à 18 23 36](https://user-images.githubusercontent.com/10850944/77936867-cc44e100-72b3-11ea-821b-e66cb72ed8f2.jpg)
![Capture d’écran 2020-03-30 à 18 21 08](https://user-images.githubusercontent.com/10850944/77936874-ce0ea480-72b3-11ea-8612-a75b90f29177.jpg)
![Capture d’écran 2020-03-30 à 18 21 03](https://user-images.githubusercontent.com/10850944/77936876-cea73b00-72b3-11ea-8457-3ae984318f8b.jpg)

**Comment by alcaeus** [comment] 2020-04-17 14:23
Closing here as this seems to be an issue with MAMP. Please follow up if it turns out to be an issue with the extension so we can investigate this some more.

**Closed by alcaeus** 2020-04-17 14:23 UTC
Labels: waiting-for-user
