### ISSUE TITLE
MongoDB\BSON\UTCDateTime::__construct returns wrong reflection information

### ISSUE THREAD

**Issue by alcaeus** [mongodb/mongo-php-driver#683] opened 2017-12-01 09:14 UTC
The method reflection for MongoDB\BSON\UTCDateTime::__construct reports that the `$milliseconds` argument does not have a default value:

```
php > var_dump(phpversion('mongodb'));
php shell code:1:
string(5) "1.3.3"

php > $reflection = new ReflectionMethod(MongoDB\BSON\UTCDateTime::class, '__construct');

php > var_dump($reflection->getParameters()[0]);
php shell code:1:
class ReflectionParameter#2 (1) {
  public $name =>
  string(12) "milliseconds"
}

php > var_dump($reflection->getParameters()[0]->isDefaultValueAvailable());
php shell code:1:
bool(false)
```

This creates issues when running static analyzers like `phpstan` on the code, which erroneously reports the following error when running `new MongoDB\BSON\UTCDateTime()`:

```
Class MongoDB\BSON\UTCDateTime constructor invoked with 0 parameters, 1 required.
```

**Comment by derickr** [comment] 2017-12-01 12:09
It looks like the problem is that we mark it as "required" and not "optional". There is no real "default value" to speak of.

I've created a ticket: https://jira.mongodb.org/browse/PHPC-1053
And a PR: https://github.com/mongodb/mongo-php-driver/pull/684

**Comment by alcaeus** [comment] 2017-12-01 12:47
@derickr thanks for the quick fix! 👍

**Comment by jmikola** [comment] 2017-12-01 18:46
[1.3.4](https://github.com/mongodb/mongo-php-driver/releases/tag/1.3.4) is released with the fix.

**Closed by jmikola** 2017-12-01 18:46 UTC
