### ISSUE TITLE
Query returns only id not the fields specified.

### ISSUE THREAD

**Issue by ccovey** [mongodb/mongo-php-driver#294] opened 2016-04-09 03:24 UTC
We have the following query.

```mongo
$lovesArray = $this->getLovesCollection()
     ->findOne(
           ['_id' => new \MongoId($loves->getId())],
           ['loveItems' => ['$elemMatch' => ['sellable.$id' => new \MongoId($sellable->getId())]]]
      );
```

Using mongdb (and the mongo-php-adapter) I get the following array back.
```
array:1 [
  "_id" => MongoId {#17769
    -objectID: MongoDB\BSON\ObjectID {#17287}
  }
]
```
But with the old driver I receive the data as expected. 
```
array:2 [
  "_id" => MongoId {#16617
    +$id: "570873273ec93556800041b7"
  }
  "loveItems" => array:1 [
    0 => array:4 [
      "_id" => MongoId {#16619
        +$id: "570873273ec93556800041be"
      }
      "sellable" => array:3 [
        "$ref" => "sellables"
        "$id" => MongoId {#16571
          +$id: "570873273ec93556800041b8"
        }
        "$db" => "opensky_devo_test"
      ]
      "createdAt" => MongoDate {#17015
        +sec: 1460171559
        +usec: 876000
      }
      "status" => "manually_added"
    ]
  ]
]
```
Also of note, I'm not 100% sure if this is a driver bug or a bug in the adapter. If this is not from the driver just let me know I'll close and move to the adapter repo.

**Comment by jmikola** [comment] 2016-04-12 19:48
We have a number of tests for query projections in the driver, so I'd defer to @alcaeus to confirm whether this a bug in [mongo-php-adapter](https://github.com/alcaeus/mongo-php-adapter). If possible, I'm sure he'd appreciate it if you could turn this into a PHPUnit test case.

**Comment by alcaeus** [comment] 2016-04-13 04:40
Thanks for bringing this to my attention, @jmikola. I've confirmed the issue exists and I'm trying to figure out whether it's due to a bug in mongo-php-adapter or somewhere else. I'll update here and in the linked ticket once I know more.

**Comment by alcaeus** [comment] 2016-04-13 04:49
Update: this is indeed a bug with mongo-php-adapter, being fixed in alcaeus/mongo-php-adapter#98. The error occurs when using BSON types in query projections, which were not properly converted to the new types.

**Comment by alcaeus** [comment] 2016-04-13 13:15
Last update: 1.0.3 of mongo-php-adapter containing a fix was released.

**Comment by ccovey** [comment] 2016-04-13 22:23
I'm sure @alcaeus hates me at this point but thanks a ton for your hard work!

**Comment by jmikola** [comment] 2016-04-14 16:46
Thanks, @alcaeus! :+1:

**Closed by jmikola** 2016-04-14 16:46 UTC
Labels: waiting-for-user
