### ISSUE TITLE
Driver on Debian 8

### ISSUE THREAD

**Issue by thibaultfalque** [mongodb/mongo-php-driver#478] opened 2016-12-04 22:34 UTC
Hello, 
### Description

I try to install the php mongodb driver in my server. But I have this error 
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php5/20131226/mongodb.so' - /usr/lib/php5/20131226/mongodb.so: undefined symbol: php_json_serializable_ce in Unknown on line 0
I use Symfony and must have the the mondb.so and not mongo.so. 
I have install this driver with pecl: 
pecl install mongodb

I create this file: /etc/php5/mods-available/mongodb.ini with this content: 
extension=mongodb.so
I execute this command: 
sudo ln -sv /etc/php5/mods-available/mongodb.ini /etc/php5/cli/conf.d/20-mongodb.ini
sudo ln -sv /etc/php5/mods-available/mongodb.ini /etc/php5/apache2/conf.d/20-mongodb.ini

### Environment
$php - i| grep mongodb
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php5/20131226/mongodb.so' - /usr/lib/php5/20131226/mongodb.so: undefined symbol: php_json_serializable_ce in Unknown on line 0

/etc/php5/cli/conf.d/20-mongodb.ini,
mongodb
mongodb support => enabled
mongodb version => 1.2.0
mongodb stability => stable
mongodb.debug => no value => no value

$php -m 
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php5/20131226/mongodb.so' - /usr/lib/php5/20131226/mongodb.so: undefined symbol: php_json_serializable_ce in Unknown on line 0
[PHP Modules]
bcmath
bz2
calendar
Core
ctype
curl
date
dba
dom
ereg
exif
fileinfo
filter
ftp
gettext
hash
iconv
intl
json
libxml
mbstring
mhash
mongodb
mysql
mysqli
openssl
pcntl
pcre
PDO
pdo_mysql
Phar
posix
readline
Reflection
session
shmop
SimpleXML
soap
sockets
SPL
standard
sysvmsg
sysvsem
sysvshm
tokenizer
wddx
xml
xmlreader
xmlwriter
Zend OPcache
zip
zlib
[Zend Modules]
Zend OPcache

Thank you for your help.

**Comment by Visualq** [comment] 2016-12-04 22:38
Hi, read https://derickrethans.nl/

**Comment by thibaultfalque** [comment] 2016-12-04 22:42
Hi,
I have read this link before write this issue. I dont't know why this solution not work... 
Thank you.

**Comment by derickr** [comment] 2016-12-04 22:55
In which file is the json.so extension loaded?

**Comment by thibaultfalque** [comment] 2016-12-05 12:28
Hello, 
This extension was loaded in  /etc/php5/mods-available/json.ini adn I have  /etc/php5/apache2/20-json.ini

Thank you.

**Comment by derickr** [comment] 2016-12-05 12:39
You speak about "php5/apache2" here, but earlier in your issue you wrote "php5/cli". You should make sure that in *either* case, the json.ini (which loads json.so) is loaded before the mongodb.so in the mongodb.ini. I would recommend you change 20-mongodb.ini to 50-mongodb.ini to make sure it gets sorted, and to make sure that there is no other extension=mongodb.so in any other ini file under /etc/php5

**Comment by thibaultfalque** [comment] 2016-12-05 12:54
Yes it's an error 
sudo ln -sv /etc/php5/mods-available/mongodb.ini /etc/php5/cli/conf.d/20-mongodb.ini
sudo ln -sv /etc/php5/mods-available/mongodb.ini /etc/php5/**apache2**/conf.d/20-mongodb.ini 

I test your solution of rename file. Thank you.

**Comment by thibaultfalque** [comment] 2016-12-05 17:11
I have edit this file: **/etc/php5/mods-available/mongodb.ini**
; priority=50
extension=/usr/lib/php5/20131226/mongodb.so

I have remove all mongdb file in **/etc/php5/apache2/conf.d/mongodb.ini** and **/etc/php5/cli/conf.d/mongodb.ini**. 

I have executed this command: php5enmod mongodb
and 
service apache2 restart 

But we have always this error: 
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php5/20131226/mongodb.so' - /usr/lib/php5/20131226/mongodb.so: undefined symbol: php_json_serializable_ce in Unknown on line 0

Thank you for your help.

**Comment by jmikola** [comment] 2016-12-05 17:33
@thibaultfalque: Please share the following:

```
$ grep -r "json.so" /etc/php5
$ grep -r "mongodb.so" /etc/php5
```

I'm not familiar with your environment, but this is most certainly caused by the MongoDB extension being loaded _after_ the JSON extension.

**Comment by thibaultfalque** [comment] 2016-12-05 17:50
Thank you everyone for your answer. 
@jmikola I have a line in cli/php.ini with mongdb extension it's the problem. Thank you!
But my problem now is composer not detect the installation of mongodb for doctrine. 
 - doctrine/mongodb 1.4.x-dev requires ext-mongo ^1.5 -> the requested PHP extension mongo is missing from your system.
    - doctrine/mongodb 1.4.x-dev requires ext-mongo ^1.5 -> the requested PHP extension mongo is missing from your system.

The doctrine mongodb use the package mongo and not mongodb ?

**Comment by jmikola** [comment] 2016-12-05 18:00
The 1.x versions of Doctrine MongoDB and Doctrine MongoDB ODM both depend on `ext-mongo` (legacy extension). If you want to use them with the `ext-mongodb` driver, you will need to install [alcaeus/mongo-php-adapter](https://github.com/alcaeus/mongo-php-adapter) as well, which implements the legacy extension's API atop the new driver and library.

If installing the adapter library does not immediately resolve the issue, you may be affected by the Composer issue described in https://github.com/doctrine/mongodb/issues/269#issuecomment-230274969.

Since the original issue has been resolved, I will close this issue.

**Closed by jmikola** 2016-12-05 18:00 UTC
