### ISSUE TITLE
How to select distinct in mongo-php-driver?

### ISSUE THREAD

**Issue by chaipipatP** [mongodb/mongo-php-driver#832] opened 2018-05-16 05:25 UTC
How to select distinct in mongo-php-driver?
[](https://docs.mongodb.com/manual/reference/method/db.collection.distinct/)

**Comment by jmikola** [comment] 2018-05-16 14:07
Closing this as a duplicate of https://github.com/mongodb/mongo-php-library/issues/535. Please do not open duplicate issues in both the driver and library projects. We monitor both projects for activity.

**Closed by jmikola** 2018-05-16 14:07 UTC
