### ISSUE TITLE
PHP 7.1 (VC14) mongodb php drive 1.3.x issue

### ISSUE THREAD

**Issue by karam89** [mongodb/mongo-php-driver#677] opened 2017-11-23 08:47 UTC
### Description

I'm trying to install `mongodb php drive 1.3.3` with PHP 7.1 (VC14) ts x86
I've tried lots of version, the only version that worked to me is 1.3.0, the later versions didn't work well

### Environment

PHP Version: 7.1.11 ThreadSafe x86
OS: Windows 10
Apache Version: 2.4.29
Working Version: https://pecl.php.net/package/mongodb/1.3.0/windows
Not Working Versions: Newer than 1.3.0

### More details

If I try to use newer version than 1.3.0, the mongodb is not loaded and the following warning is logged to apache:
```
PHP Warning:  PHP Startup: Unable to load dynamic library 'C:\\Apache24\\PHP\\ext\\php_mongodb.dll' - The specified module could not be found.\r\n in Unknown on line 0
```

but if I try with 1.3.0, the mongodb php driver works well

**Note**
Of course I'm choosing **x86 ts** from the mongodb download page

> and even If I try nts or x64, the module will not load, and other message is logged to apache telling that I'm trying wrong version

**Comment by jmikola** [comment] 2017-11-27 18:11
I attempted to reproduce this with the following packages:

 * https://www.apachelounge.com/download/VC15/binaries/httpd-2.4.29-Win32-VC15.zip
 * http://windows.php.net/downloads/releases/php-7.1.12-nts-Win32-VC14-x86.zip
 * http://windows.php.net/downloads/pecl/releases/mongodb/1.3.3/php_mongodb-1.3.3-7.1-ts-vc14-x86.zip

I unpacked Apache to `c:/Apache24/`, PHP to `c:/Apache24/php/`, and the MongoDB driver to `c:/Apache24/php/ext`, respectively.

I configured PHP in Apache by adding the following to the bottom of `c:/Apache24/conf/httpd.conf`:

```
LoadModule php7_module c:/Apache24/php/php7apache2_4.dll
AddType application/x-httpd-php .php
PHPIniDir "c:/Apache24/php/"
```

The Windows builds of PHP do not ship with a `php.ini` file, so I first copied `php.ini-development` to `php.ini` (within `c:/Apache24/php/`). I then added the following to the bottom of `php.ini`:

```
extension_dir=c:/Apache24/php/ext;
extension=php_mongodb.dll;
```

I then created `c:/Apache24/htdocs/test.php` with the following content:

```php
<?php

var_dump(new MongoDB\Driver\Manager);

phpinfo();
```

Finally, I launched `c:/Apache24/bin/httpd.exe` and opened `http://localhost/test.php` in a browser. I then saw the expected `var_dump()` output for a Manager object, followed by `phpinfo()` output, which also confirmed that the `mongodb` extension was loaded.

**Comment by Gemorroj** [comment] 2018-01-17 11:01
same problem.
```cmd
s:\OpenServer\modules\php\PHP-7.1-x64>php -v
ext\mongodb\src\libmongoc\src\mongoc\mongoc-init.c:117 _mongoc_do_init(): precondition failed: status == SASL_OK
```

**Comment by Gemorroj** [comment] 2018-02-17 10:03
@jmikola 
windows 10 x64
- download http://windows.php.net/downloads/releases/php-7.1.14-Win32-VC14-x64.zip
- download http://windows.php.net/downloads/pecl/releases/mongodb/1.3.4/php_mongodb-1.3.4-7.1-ts-vc14-x64.zip or http://windows.php.net/downloads/pecl/releases/mongodb/1.4.0/php_mongodb-1.4.0-7.1-ts-vc14-x64.zip (any 1.3.* or 1.4.0 release).
- unpack `php-7.1.14-Win32-VC14-x64.zip`
- unpack `php_mongodb` extension and move `php_mongodb.dll` into `ext` directory.
- rename `php.ini-development` into `php.ini`
- uncomment `extension_dir = "ext"`
- add `extension=php_mongodb.dll`
- execute `php -v`

![mongo](https://user-images.githubusercontent.com/885731/36340001-f06b02b2-13e2-11e8-8eef-b57f0ca1003b.png)

**Comment by jmikola** [comment] 2018-02-20 18:37
@Gemorroj: The issue you're describing appears to be distinct from the OP's error ("The specified module could not be found"). Please open a separate issue and so we can track that independently.

I was not able to reproduce the [assertion failure](https://github.com/mongodb/mongo-c-driver/blob/1.9.2/src/mongoc/mongoc-init.c#L112) using the steps in https://github.com/mongodb/mongo-php-driver/issues/677#issuecomment-366430775 on Windows 7; however, I can attempt reproduction with Windows 10 and follow up once the new issue is created.

As for the original issue, I'm closing this thread since we never heard back on https://github.com/mongodb/mongo-php-driver/issues/677#issuecomment-347272819.

**Closed by jmikola** 2018-02-20 18:37 UTC
Labels: waiting-for-user

**Comment by lerislentia** [comment] 2019-09-17 08:59
why dont share your php.ini file instead of close topic

**Comment by nspeedzy** [comment] 2020-07-26 06:03
Hello I am getting the same problem now! I tried adding `extension=php_mongodb.dll` to my `php.ini` but it just doesn't work!

**Comment by alcaeus** [comment] 2020-07-27 06:39
@nspeedzy please create a new issue, providing ALL information asked for in the issue template. As this issue has run its course two years ago, I'm locking it to prevent further necromancing.
