### ISSUE TITLE
Having Problem with $collection->remove($criteria)

### ISSUE THREAD

**Issue by rejudy** [mongodb/mongo-php-driver#200] opened 2016-01-09 21:53 UTC
I am using XAMPP with Windows 7. I am using array("name"=>"Learn more PHP") for the criteria. I am not using any options. I have no problem deleting a document with the Mongo shell using the equivalent criteria. I also have no problem with queries or inserting documents using PHP.

**Comment by jmikola** [comment] 2016-01-11 02:19
You'll need to be more specific about the problem you're experiencing. All I'm reading if that you're using the aforementioned criteria array without options.

What does the returned DeleteResult object report from its `getDeletedCount()` method? I assume it is zero and you expect it to be non-zero? Do you have a full script you can share to reproduce whatever problem you're seeing?

**Comment by jmikola** [comment] 2016-02-09 01:58
Closing due to no follow-up. If you have more information, please open a new issue on the [mongo-php-library](https://github.com/mongodb/mongo-php-library) project, which you appear to be using (this extension doesn't provide the Database or Collection classes or any high-level CRUD API).

**Closed by jmikola** 2016-02-09 01:58 UTC
