### ISSUE TITLE
E11000 duplicate key error, running in parallel, MongoDB extension 1.6.1

### ISSUE THREAD

**Issue by vkatochka** [mongodb/mongo-php-driver#1104] opened 2020-02-26 21:09 UTC
Description: Ubuntu 18.04.4 LTS
PHP 7.2.24-0ubuntu0.18.04.3 (cli)
Python 3.6.9

Standalone MongoDB v4.0.16
MongoDB extension 1.6.1
MongoDB PHP Library 1.5.2

The wrk.php file contains something like this:
~~~
$mnc = new MongoDB\Client();
$dbc = $mnc->selectDatabase();

foreach(...)
{
	foreach(['mycol1','mycol2','mycol3'] as $name)
	{
		$data = [
			'field1' => 'value1',
			'field2' => 'value1',
			'field3' => 'value1',
			'field4' => 'value1',
		];
	
		$rs = $dbc->selectCollection($name)->insertOne($data);
	}
}
~~~

Six wrk.php files run in parallel (6 threads). Each file contains an identical code.
Each wrk.php file in foreach inserts ~ 12000 entries into three collections. Waits for the insert to complete in all 6 files. Next, the next six are launched, and so on.

Sometimes such an error occurs ():
~~~
PHP Fatal error:  Uncaught MongoDB\Driver\Exception\BulkWriteException: E11000 duplicate key error collection: mydb.mycol index: _id_ dup key: { : ObjectId('5e568b6ff8742568910da4d2') } in /.../composer/mongodb/mongodb/vendor/mongodb/mongodb/src/Operation/InsertOne.php:114
Stack trace:
#0 /.../composer/mongodb/mongodb/vendor/mongodb/mongodb/src/Operation/InsertOne.php(114): MongoDB\Driver\Server->executeBulkWrite('mydb.mycol', Object(MongoDB\Driver\BulkWrite), Array)
#1 /.../composer/mongodb/mongodb/vendor/mongodb/mongodb/src/Collection.php(892): MongoDB\Operation\InsertOne->execute(Object(MongoDB\Driver\Server))
#2 /.../utils/console/wrk.php(299): MongoDB\Collection->insertOne(Array)
#3 {main}
  thrown in /.../composer/mongodb/mongodb/vendor/mongodb/mongodb/src/Operation/InsertOne.php on line 114
~~~

Prior to this, the script worked for more than 3 months with the version 1.5.5 of "MongoDB extension", and there was no such problem.

Thanks

> The [ObjectID spec](https://github.com/mongodb/specifications/blob/master/source/objectid.rst) was introduced in ext-mongodb 1.5.0. The reason I'm mentioning this is because this changed how ObjectIds are generated: the 3-byte machine identifier and 2-byte process identifier were replaced with a 5-byte random value. This random value is generated once per process. To avoid collisions when generating multiple ObjectIDs in a single second, the last 3 bytes of the ObjectId are a counter. This is initialised to a random value when the driver is loaded, then incremented after every ObjectId generation.
> 
> Since you mentioned that you use threads, I checked how the driver behaves there with a script:
> 
> ```
> var_dump(new MongoDB\BSON\ObjectId());
> 
> $pid = pcntl_fork();
> 
> var_dump($pid, new MongoDB\BSON\ObjectId());
> var_dump($pid, new MongoDB\BSON\ObjectId());
> ```
> 
> The output confirms what I saw in the code. First, a single ObjectId is generated:
> 
> ```
> class MongoDB\BSON\ObjectId#1 (1) {
>   public $oid =>
>   string(24) "5e576ba988846945965b4a41"
> }
> ```
> 
> The timestamp is `5e576ba9`, the random value has been set to `8884694596`, and the counter has been initialised to `5b4a41`.
> 
> After the fork, a total of 4 ObjectIds are generated, 2 in each parent and child threads. I dumped the return value of `pcntl_fork()` to know which thread generated them. The first two ObjectIds were generated by the parent, the next two by the client:
> 
> ```
> class MongoDB\BSON\ObjectId#1 (1) {
>   public $oid =>
>   string(24) "5e576ba988846945965b4a42"
> }
> class MongoDB\BSON\ObjectId#1 (1) {
>   public $oid =>
>   string(24) "5e576ba988846945965b4a43"
> }
> class MongoDB\BSON\ObjectId#1 (1) {
>   public $oid =>
>   string(24) "5e576ba9ca229138cd5b4a42"
> }
> class MongoDB\BSON\ObjectId#1 (1) {
>   public $oid =>
>   string(24) "5e576ba9ca229138cd5b4a43"
> }
> ```
> 
> Looking at these ObjectIds, we can see that the timestamp is the same (as expected). We can also see that while the counter is the same for each pair of IDs created in parent and child, the child thread's random value has been re-initialised to `ca229138cd`. This is consistent with logic in libmongoc (which is responsible for ObjectId generation), which by default re-initialises the random value: https://github.com/mongodb/mongo-c-driver/blob/535e9091f399fbea2cacab490b93fbed48c328be/src/libbson/src/bson/bson-context.c#L201.
> 
> I tested the above script on 1.6.1 and 1.7.3 and was not able to reproduce a duplicate ObjectId, but that may be a question of sample size.
> 
> For now, I would suggest that you upgrade to the latest version of ext-mongodb (1.7.3). The platform requirements stayed the same (both support 5.6+), so that shouldn't cause any issues. If this solves the problem, let's just chalk it up to bad luck.
> 
> If it doesn't solve the problem, you always have the opportunity to generate your own identifiers. For this purpose, UUIDv4 is a good choice, as it's designed to avoid collisions in an environment like you have it. You can store the identifier as a `MongoDB\BSON\Binary` with subtype 4 (`MongoDB\BSON\Binary::TYPE_UUID`).

**Comment by alcaeus** [comment] 2020-02-27 07:28
The [ObjectID spec](https://github.com/mongodb/specifications/blob/master/source/objectid.rst) was introduced in ext-mongodb 1.5.0. The reason I'm mentioning this is because this changed how ObjectIds are generated: the 3-byte machine identifier and 2-byte process identifier were replaced with a 5-byte random value. This random value is generated once per process. To avoid collisions when generating multiple ObjectIDs in a single second, the last 3 bytes of the ObjectId are a counter. This is initialised to a random value when the driver is loaded, then incremented after every ObjectId generation.

Since you mentioned that you use threads, I checked how the driver behaves there with a script:
```php
var_dump(new MongoDB\BSON\ObjectId());

$pid = pcntl_fork();

var_dump($pid, new MongoDB\BSON\ObjectId());
var_dump($pid, new MongoDB\BSON\ObjectId());
```

The output confirms what I saw in the code. First, a single ObjectId is generated:
```
class MongoDB\BSON\ObjectId#1 (1) {
  public $oid =>
  string(24) "5e576ba988846945965b4a41"
}
```

The timestamp is `5e576ba9`, the random value has been set to `8884694596`, and the counter has been initialised to `5b4a41`.

After the fork, a total of 4 ObjectIds are generated, 2 in each parent and child threads. I dumped the return value of `pcntl_fork()` to know which thread generated them. The first two ObjectIds were generated by the parent, the next two by the client:
```
class MongoDB\BSON\ObjectId#1 (1) {
  public $oid =>
  string(24) "5e576ba988846945965b4a42"
}
class MongoDB\BSON\ObjectId#1 (1) {
  public $oid =>
  string(24) "5e576ba988846945965b4a43"
}
class MongoDB\BSON\ObjectId#1 (1) {
  public $oid =>
  string(24) "5e576ba9ca229138cd5b4a42"
}
class MongoDB\BSON\ObjectId#1 (1) {
  public $oid =>
  string(24) "5e576ba9ca229138cd5b4a43"
}
```

Looking at these ObjectIds, we can see that the timestamp is the same (as expected). We can also see that while the counter is the same for each pair of IDs created in parent and child, the child thread's random value has been re-initialised to `ca229138cd`. This is consistent with logic in libmongoc (which is responsible for ObjectId generation), which by default re-initialises the random value: https://github.com/mongodb/mongo-c-driver/blob/535e9091f399fbea2cacab490b93fbed48c328be/src/libbson/src/bson/bson-context.c#L201.

I tested the above script on 1.6.1 and 1.7.3 and was not able to reproduce a duplicate ObjectId, but that may be a question of sample size.

For now, I would suggest that you upgrade to the latest version of ext-mongodb (1.7.3). The platform requirements stayed the same (both support 5.6+), so that shouldn't cause any issues. If this solves the problem, let's just chalk it up to bad luck.

If it doesn't solve the problem, you always have the opportunity to generate your own identifiers. For this purpose, UUIDv4 is a good choice, as it's designed to avoid collisions in an environment like you have it. You can store the identifier as a `MongoDB\BSON\Binary` with subtype 4 (`MongoDB\BSON\Binary::TYPE_UUID`).

**Comment by vkatochka** [comment] 2020-02-27 12:29
> I tested the above script on 1.6.1 and 1.7.3 and was not able to reproduce a duplicate ObjectId, but that may be a question of sample size.

I checked on 1.6.1, 1.7.3, duplicates appear. I will prepare a script that reproduces this.

**Comment by vkatochka** [comment] 2020-03-02 18:56
A video with running the script on 1.6.1, 1.7.3 is available here: [https://fex.net/s/nbmkomn](url).
The second video seems that everything is good ... but a little later it turns out that not everything is good.

bug.py
~~~
#!/usr/bin/env python3
# -*- coding: utf-8 -*-

#
import os
import sys
import time
import subprocess


#
os.environ['TZ'] = 'UTC'; time.tzset()

#
'''
itms = [
	[1,2,3,4,5,6],
	[1,2,3,4,5,6],
	[1,2,3,4,5,6],
	[1,2,3,4,5,6],
	[1,2,3,4,5,6],
]
'''

#
itms = [[1,2,3,4,5,6] for i in range(0,30)]


#
j=0

#
for i,item in enumerate(itms):
	
	#
	j+=1
	
	#
	print(f"\n  Wait when all workers are finished:", flush=True)
	
	#
	proc = []
	
	#
	for k,file in enumerate(item):
		pres = subprocess.Popen(('/usr/bin/php', 'bugwrk.php'))
		proc.insert(k,pres)
	
	#
	for k,file in enumerate(item):
		proc[k].wait()
	
	#
	print(f"\n    Cycle #{j} completed", flush=True)
	
#
print('  All chunks processed!', flush=True)
~~~

bugwrk.php
~~~
<?php

#
set_time_limit(0);
mb_internal_encoding('UTF-8');
date_default_timezone_set('UTC');
ini_set('display_errors', 1);


#
if (file_exists('./composer/mongodb/mongodb/vendor/autoload.php'))
{
	include('./composer/mongodb/mongodb/vendor/autoload.php');
}

#
try
{
	$mnc = new MongoDB\Client('mongodb://127.0.0.1:27017');
	$dbc = $mnc->selectDatabase('bug');
}
catch (MongoConnectionException $e)
{
	print_r($e); exit();
}


#
$timer = date_create();

#
foreach(range(1,6000) as $i)
{
	#
	foreach(['mc1','mc2','mc3'] as $name)
	{
		#
		$data = [
			'id' => $i,
			'aa' => [],
			'bb' => [],
			'cc' => [],
		];
		
		#
		try
		{
			$dbc->selectCollection($name)->insertOne($data);
		}
		catch(Exception $e)
		{
			#
			$code = $e->getCode();
			$mesg = $e->getMessage();
			
			#
			print("\n{$i}:{$name}: {$code}{$mesg}");
		}
	}
}

print("\n    Time: ". (date_diff(date_create(), $timer)->format('%h:%I:%S')) ." worker done!");

?>
~~~


> mkdir tmp_dir
> cp bug.py tmp_dir
> cp bugwrk.php tmp_dir
> cd tmp_dir

> mkdir -p composer/mongodb/mongodb  
> cd composer/mongodb/mongodb  
> composer require --no-plugins --no-scripts mongodb/mongodb  

> python3 bug.py

**Comment by alcaeus** [comment] 2020-03-23 12:42
I haven't tried the code above, but at first glance I didn't find an obvious problem. However, looking at the problem the previous assumption that these run in separate threads is incorrect: there are 6 separate PHP processes inserting this data, which is significantly different from a process forking to create 6 child threads that handle insertion. Starting a new PHP process always initialises a new random value in libmongoc for ObjectID generation, so I'm still not sure where this issue comes from.

With all the information given here, I would recommend manually generating identifiers and seeing if the problem persists. While ObjectID generation should avoid this issue, we generally don't recommend people rely on auto-generated identifiers, instead generating identifiers (e.g. UUID) themselves.

Alternatively, you may also want to ask in the new [MongoDB Developer Community Forums](https://community.mongodb.com) to see if somebody else has encountered this problem before. I'm closing this issue here since I can't reproduce it as a bug.

**Closed by alcaeus** 2020-03-23 12:42 UTC
