### ISSUE TITLE
Argument 3 passed to MongoDB\Driver\Server::executeQuery()

### ISSUE THREAD

**Issue by MNSolderstar** [mongodb/mongo-php-driver#824] opened 2018-04-30 14:24 UTC
### Description

Type error: Argument 3 passed to MongoDB\Driver\Server::executeQuery() must be an instance of MongoDB\Driver\ReadPreference or null, array given
/home/vagrant/code/vendor/mongodb/mongodb/src/Operation/Find.php:287

### Environment

Laravel 5.6.18
Homestead 5.2.0

mongodb
libbson bundled version => 1.8.2
libmongoc bundled version => 1.8.2
libmongoc SSL => enabled
libmongoc SSL library => OpenSSL
libmongoc crypto => enabled
libmongoc crypto library => libcrypto
libmongoc crypto system profile => disabled
libmongoc SASL => enabled
mongodb.debug => no value => no value

[PHP Modules]
bcmath
blackfire
calendar
Core
ctype
curl
date
dom
exif
fileinfo
filter
ftp
gd
gettext
hash
iconv
igbinary
imap
intl
json
libxml
mbstring
memcached
mongodb
msgpack
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
pdo_pgsql
pdo_sqlite
pgsql
Phar
posix
readline
Reflection
session
shmop
SimpleXML
soap
sockets
sodium
SPL
sqlite3
standard
sysvmsg
sysvsem
sysvshm
tokenizer
wddx
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache
blackfire

### Code Snippet

Using https://github.com/jenssegers/laravel-mongodb

```php
return Organisation::all();
```

### Error

```
Type error: Argument 3 passed to MongoDB\Driver\Server::executeQuery() must be an instance of MongoDB\Driver\ReadPreference or null, array given
/home/vagrant/code/vendor/mongodb/mongodb/src/Operation/Find.php:287
```

### Fix

vendor/mongodb/mongodb/src/Operation/Find.php:287

Replace:

```php
$cursor = $server->executeQuery($this->databaseName . '.' . $this->collectionName, $this->createQuery(), $this->createOptions());
```
With:

```php
$cursor = $server->executeQuery($this->databaseName . '.' . $this->collectionName, $this->createQuery(), $this->options['readPreference']);
```

**Comment by jmikola** [comment] 2018-04-30 14:55
"MongoDB extension version" appears to be missing from your `phpinfo()` output, but I assume you're using 1.3.3 or 1.3.4, as [1.3.3](https://pecl.php.net/package/mongodb/1.3.3) was the version that bumped the libmongoc dependency to 1.8.2.

The error you're seeing is caused by using [mongo-php-library](https://github.com/mongodb/mongo-php-library) (package: `mongodb/mongodb`) 1.3.0+ with an older version of the driver. If you look at [`mongodb/mongodb` in Packagist](https://packagist.org/packages/mongodb/mongodb), you'll see that it requires `ext-mongodb` 1.4.0+. If you ran [`composer update`](https://getcomposer.org/doc/03-cli.md#update), it should have caught this for you (unless you were also using `--ignore-platform-reqs`).

In any event, upgrading the [`mongodb` extension](https://pecl.php.net/package/mongodb/) to 1.4.x should resolve this.

**Comment by MNSolderstar** [comment] 2018-04-30 15:48
I need to figure out what version of the mongo-db extension homestead has provisioned.
My local interpreter is actually using mongo 1.4.3 so composer update is satisfied on update.

Ill check the provision script and get back to you. Cheers for pointing me in general direction.

**Comment by MNSolderstar** [comment] 2018-04-30 16:36
For anyone else using Laravel Homestead and having this error you can check your mongodb extension version by doing: 

```php
<?php
echo phpversion("mongodb");
```

If this prints anything lower than 1.4.0 then you can update your Homestead via SSH.

```
sudo pecl channel-update pecl.php.net
sudo pecl install mongodb
```
Restart VM from terminal in your project dir:

```
vagrant reload
```

**Comment by jmikola** [comment] 2018-04-30 16:48
I'm not familiar with Homestead, but I believe https://github.com/laravel/homestead/pull/840 is the relevant issue for it upgrading the bundled extension to 1.4.0.

Closing this out, as there is no issue with the driver/library here.

**Closed by jmikola** 2018-04-30 16:48 UTC

**Comment by chandanrao611** [comment] 2019-07-28 07:04
vendor/mongodb/mongodb/src/Operation/Find.php
 Open this file and search 
$cursor = $server->executeQuery($this->databaseName . '.' . $this->collectionName, new Query($this->filter, $this->createQueryOptions()), $this->createExecuteOptions());

this line replace with below code
        $cursor = $server->executeQuery($this->databaseName . '.' . $this->collectionName, new Query($this->filter, $this->createQueryOptions()), $this->options['readPreference']);

Arfter it run the command
php artisan serve
Working fine

**Comment by jmikola** [comment] 2019-07-29 06:30
@chandanrao611: The [`createExecuteOptions()`](https://github.com/mongodb/mongo-php-library/blob/1.4.3/src/Operation/Find.php#L359) method does more than just set the read preference. It also prepares the session option, which means that your patch could inadvertently break any queries relying on sessions (e.g. within a multi-document transaction).

The root cause of this issue was due to the installed extension being too old for the library, and the OP somehow missing Composer's notification that the installed version was not adequate (since extension requirements are noted in `composer.json`).

https://github.com/mongodb/mongo-php-library/commit/142d24ecebbd7c60c8a8f592727aa6878515d061#diff-2bfb552f851648971366b9269219e2c6 is the commit that introduced the `createExecuteOptions()` method and changed the third argument to an array when session support was introduced in [1.3.0](https://github.com/mongodb/mongo-php-library/releases/tag/1.3.0). Using a previous version of the library would be preferable to manually patching it in your project; however, the best solution would be to upgrade the extension itself to a version compatible with the library you've installed.

**Comment by sameermistry2502** [comment] 2020-10-20 05:55
> vendor/mongodb/mongodb/src/Operation/Find.php
> Open this file and search
> $cursor = $server->executeQuery($this->databaseName . '.' . $this->collectionName, new Query($this->filter, $this->createQueryOptions()), $this->createExecuteOptions());
> 
> this line replace with below code
> $cursor = $server->executeQuery($this->databaseName . '.' . $this->collectionName, new Query($this->filter, $this->createQueryOptions()), $this->options['readPreference']);
> 
> @chandanrao611 solution is Working fine .I am getting same issue .I have resolved it by this solution
